version: 2
jobs:
  build:
    docker:
      - image: diehlpk/teaching
    steps:
      - checkout
      - run: find -name "*.cpp" -exec g++ "{}" -o "{}".exec ";"
      - run: find -name "*.cpp" -exec cppcheck --enable=warning,performance "{}" ";"
      - run: mkdir final 
      - run: 
          command: | 
            make
            cp book.pdf final
      - store_artifacts:
          path: final
          destination: book
